hwi_oauth:
  firewall_names: [main]

  resource_owners:
      google:
          type:                google
          client_id:           2971345214-vdlubhnnsmgfsb35d38231rju1ds9jmr.apps.googleusercontent.com
          client_secret:       LxjWVXMTP4csuX2WnngE1mn7
          scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
          options:
              access_type:     offline
              csrf:            true