security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        db_provider:
            id: App\Security\User\OwnUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
#        not_secured_area:
#            pattern: ^/error
#            security: false
        main:
            pattern:    ^/
            provider: db_provider
            logout:
                delete_cookies:
                    googleId: { path: null, domain: null }
            user_checker: App\Security\UserChecker
            oauth:
                resource_owners:
                    google:             "/login/google"
                login_path:        /error/404
                use_forward:       false
                failure_path:      /error/404
                oauth_user_provider:
                     service: App\Security\User\OwnAuthUserProvider
            guard:
                authenticators:
                    - App\Security\CustomAuthenticator
