controllers:
    resource: ../../src/Controller/
    type: annotation

ajaxcontrollers:
    resource: ../../src/AjaxController/
    type: annotation

croncontrollers:
    resource: ../../src/CronController/
    type: annotation